#import "../_fragments/Users.gql"

query users {
  users {
    total
    users {
      _id
      name {
        first
        last
      }
      roles {
        _id
        name
        inRole
      }
      username
      emailAddress
      emailVerified
      oAuthProvider
      wishlist
      itchlist
      ownlist
      subscription
      friends {
        userId
        emailAddress
      }
      loanedTo {
        _id
        userId
        emailAddress
      }
      borrowedFrom {
        _id
        userId
        emailAddress
      }
      gamePlayCounts {
        _id
        count
      }
    }
  }
}

query user($_id: String) {
  user(_id: $_id) {
    ...UserAttributes
    username
    wishlist
    itchlist
    ownlist
    subscription
    friends {
      userId
      emailAddress
    }
    loanedTo {
      _id
      userId
      emailAddress
    }
    borrowedFrom {
      _id
      userId
      emailAddress
    }
    gamePlayCounts {
      _id
      count
    }
  }
}


query userFromUsername($username: String) {
  userFromUsername(username: $username) {
    ...UserAttributes,
      username
      wishlist
      itchlist
      ownlist
      subscription
      friends {
        userId
        emailAddress
      }
      loanedTo {
        _id
        userId
        emailAddress
      }
      borrowedFrom {
        _id
        userId
        emailAddress
      }
      gamePlayCounts {
        _id
        count
      }
  }
}


query userSettings {
  user {
    settings {
      _id
      isGDPR
      key
      label
      type
      value
      lastUpdatedByUser
    }
  }
}

query exportUserData {
  exportUserData {
    zip
  }
}
